# url for [snaptortoise](https://github.com/snaptortoise/jekyll-rss-feeds)

gems:
  - jekyll-feed

repository: "tbates/Seminar_in_Personality"
# url: "https://tbates.github.io/Seminar_in_Personality"
url: "https://tbates.github.io"
baseurl: "/Seminar_in_Personality"
production_url: "https://tbates.github.io/Seminar_in_Personality"

# Note - if you enable this, use jekyll --baseurl '/' to view locally

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: "Advanced seminar-based course in Personality"
# Short description (goes below the title; it will also be used in the RSS feed)
description: "Personality. Approaches, advances, and important ideas."



