# Site settings
title: Seminar in Personality
email: tim.bates@ed.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Personality, from measurement of the the five factor model,
  to outcomes in work, family, culture, and the clinic.
baseurl: /Seminar_in_Personality # the subpath of your site, e.g. /blog
url: "https://tbates.github.io/"
twitter_username: timothycbates
github_username:  tbates
# Build settings
exclude: ["README.md"]